package th.or.set.setportal.eonereport.constants;

import lombok.Getter;

import java.util.HashMap;
import java.util.Map;

@Getter
public enum RemarkSection {
    COMPANY_INFO("company-info"),
    EXPORT_INCOME("export-income"),
    PRODUCT_INFO("product-info"),
    OTHER_INCOME("other-income"),
    SHARE_PROFIT("share-profit"),
    BAC05("bac05"),
    BUSINESS_CHARACTERISTICS("business-characteristics"),
    BC01("bc01"),
    BUSINESS_AND_CORPORATE_POLICY("business-and-corporate-policy"),
    BAC01("bac01"),
    BAC02("bac02"),
    BAC03("bac03"),
    BAC04("bac04"),
    REGISTERED_CAPITAL_AND_PAID_UP_CAPITAL("registered-capital-and-paid-up-capital"),
    RCAPC01("rcapc01"),
    RCAPC02("rcapc02"),
    RCAPC03("rcapc03"),
    DIVIDEND_POLICY("dividend-policy"),
    NET_PROFIT_PER_SHARE("net-profit-per-share"),
    DIVIDEND_PER_SHARE("dividend-per-share"),
    DIVIDEND_STOCK_RATIO("dividend-stock-ratio"),
    DIVIDEND_SHARE_VALUE_PER_SHARE("dividend-share-value-per-share"),
    ISSUANCE_OF_OTHER_SECURITIES("issuance-of-other-securities"),
    IOS01("ios01"),
    IOS02("ios02"),
    RISK_MGMT_POLICY_AND_PLAN("risk-mgmt-policy-and-plan"),
    RMPAP01("rmpap01"),
    COMPANY_RISK("company-risk"),
    HOLDER_RISK("holder-risk"),
    FOREIGN_RISK("foreign-risk"),
    RISK_FACTORS("risk-factors"),
    RF01("rf01"),
    RF02("rf02"),
    RF03("rf03"),
    STAKEHOLDERS_IMPACT_MGMT("stakeholders-impact-mgmt"),
    SIM01("sim01"),
    SIM02("sim02"),
    BC02("bc02"),
    BC0201("bc0201"),
    BC0202("bc0202"),
    BC0203("bc0203"),
    BC0204("bc0204"),
    BC0205("bc0205"),
    DOMESTIC_EXPORT_SALES_RATIO("domestic-export-sales-ratio"),
    SUSTAINABILITY_POLICY_AND_GOAL("sustainability-policy-and-goal"),
    SUSTAINABILITY_POLICY("sustainability-policy"),
    SUSTAINABILITY_GOAL("sustainability-goal"),
    REVIEWED_SUSTAINABILITY_POLICY_AND_GOAL("reviewed-sustainability-policy-and-goal"),
    ENVIRONMENTAL_SUSTAINABILITY_MGMT("environmental-sustainability-mgmt"),
    ESM01("esm01"),
    ENVIRONMENTAL_ISSUE("environmental-issue"),
    REVIEWED_POLICY("reviewed-policy"),
    ENERGY_TARGET("energy-target"),
    WATER_TARGET("water-target"),
    WASTE_TARGET("waste-target"),
    FUEL_SUMMARY("fuel-summary"),
    FUEL_SUMMARY_INFO("fuel-summary-info"),
    OTHER_ENERGY_MGMT_INFO("other-energy-mgmt-info"),
    ELECTRICITY_CONSUMPTION("electricity-consumption"),
    ELECTRICITY_SUMMARY_INFO("electricity-summary-info"),
    WATER_SUMMARY_INFO("water-summary-info"),
    WATER_CONSUMPTION("water-consumption"),
    WATER_DISCHARGE("water-discharge"),
    WATER_WITHDRAWAL("water-withdrawal"),
    RECYCLED_WATER("recycled-water"),
    TOTAL_NON_HAZARDOUS("total-non-hazardous"),
    TOTAL_HAZARDOUS("total-hazardous"),
    WASTE_SUMMARY_TOTAL("waste-summary-total"),
    GH_GAS_GOAL("gh-gas-goal"),
    GH_GAS_SCOPE1("gh-gas-scope1"),
    GH_GAS_SCOPE2("gh-gas-scope2"),
    GH_GAS_SCOPE3("gh-gas-scope3"),
    GREEN_HOUSE_GAS_SUMMARY_TOTAL("green-house-gas-summary-total"),
    VERIFY_DEPT_OF_GH_GAS("verify-dept-of-gh-gas"),
    SOCIAL_SUSTAINABILITY_MGMT("social-sustainability-mgmt"),
    HUMAN_RIGHTS_ISSUE("human-rights-issue"),
    EMPLOYEE_INFO("employee-info"),
    EMPLOYEE_REMUNERATION("employee-remuneration"),
    TRAINING_HOURS("training-hours"),
    TRAINING_EXPENSES("training-expenses"),
    OCCUPATIONAL_ACCIDENTS("occupational-accidents"),
    EMPLOYEE_RELATIONSHIP("employee-relationship"),
    EMPLOYEE_RELATIONSHIP_INFO("employee-relationship-info"),
    CUSTOMER_SATISFACTION("customer-satisfaction"),
    LABOR_DISPUTE("labor-dispute"),
    OVERVIEW_POLICIES("overview-policies"),
    OVERVIEW_POLICIES_SUB_SECTION("overview-policies-sub-section"),
    DIRECTOR_ISSUE("director-issue"),
    OP02("op02"),
    CODE_OF_CONDUCT("code-of-conduct"),
    COC01("coc01"),
    OP01("op01"),
    COC_ISSUE("coc-issue"),
    ENCOURAGE_COMPLIANCE("encourage-compliance"),
    AGAINST_FRAUD_AND_CORRUPTION("against-fraud-and-corruption"),
    CODE_OF_CONDUCT_ISSUE("code-of-conduct-issue"),
    CHANGES_AND_DEV_POLICY("changes-and-dev-policy"),
    CADP01("cadp01"),
    CADP02("cadp02"),
    CADP03("cadp03"),
    PRESENT_BOD("present-bod"),
    PAST_BOD("past-bod"),
    SAME_FAMILY("same-family"),
    INDEPENDENT_DETERMINE_AGENDA("independent-determine-agenda"),
    PRESENT_AUDIT_COMMITTEE("present-audit-committee"),
    PAST_AUDIT_COMMITTEE("past-audit-committee"),
    PRESENT_EXECUTIVE_COMMITTEE("present-executive-committee"),
    PAST_EXECUTIVE_COMMITTEE("past-executive-committee"),
    PRESENT_SUB_COMMITTEE("present-sub-committee"),
    RISK_MANAGEMENT("risk-management"),
    NOMINATION("nomination"),
    REMUNERATION("remuneration"),
    NOMINATION_REMUNERATION("nomination-remuneration"),
    SUSTAINABILITY("sustainability"),
    PRESENT_EXECUTIVE("present-executive"),
    EXECUTIVE_REMUNERATION_POLICY("executive-remuneration-policy"),
    EXECUTIVE_REMUNERATION("executive-remuneration"),
    ESOP("esop"),
    EJIP("ejip"),
    EMPLOYEE_TOTAL("employee-total"),
    NUMBER_OF_PVD("number-of-pvd"),
    PERCENT_PVD("percent-pvd"),
    INVESTOR_RELATION("investor-relation"),
    AUDITOR_INFO("auditor-info"),
    DEVELOP_DIRECTOR("develop-director"),
    ASSESSMENT("assessment"),
    DIRECTOR_MEETING("director-meeting"),
    DIRECTOR_REMUNERATION("director-remuneration"),
    ENERGY_MGMT_PERFORMANCE("energy-mgmt-performance"),
    AUDIT_COMMITTEE_MEETING("audit-committee-meeting"),
    ENERGY_MGMT_PLAN("energy-mgmt-plan"),
    ESM02("esm02"),
    ESM03("esm03"),
    WATER_MGMT_PLAN("water-mgmt-plan"),
    ESM04("esm04"),
    WASTE_MGMT_PLAN("waste-mgmt-plan"),
    ESM05("esm05"),
    WASTE_MGMT_PERFORMANCE("waste-mgmt-performance"),
    WATER_MGMT_PERFORMANCE("water-mgmt-performance"),
    WASTE_GENERATION("waste-generation"),
    REUSED_RECYCLED_WASTE("reused-recycled-waste"),
    SHAREHOLDING_STRUCTURE("shareholding-structure"),
    SS01("ss01"),
    OPERATIONAL_ORGANIZATION_POLICY("operational-organization-policy"),
    TEN_PERCENT("ten-percent"),
    SS02("ss02"),
    SS03("ss03"),
    SS04("SS04"),
    MAJOR_SHAREHOLDERS("major-shareholders"),
    SHAREHOLDER_AGREEMENT("shareholder-agreement"),
    SHAREHOLDING_DIAGRAM("shareholding-diagram"),
    POTENTIAL_FACTOR_AFFECT_FINANCIAL_CONDITION("potential-factor-affect-financial-condition"),
    POTENTIAL_FACTOR_AFFECT_FINANCIAL_CONDITION_FUTURE("potential-factor-affect-financial-condition-future"),
    PROJECT_OR_RESEARCH("project-or-research"),
    OTHER_POTENTIAL_FACTOR_AFFECT_FINANCIAL_CONDITION("other-potential-factor-affect-financial-condition"),
    SSM01("ssm01"),
    HUMAN_RIGHTS_COMPLIANCE("human-rights-compliance"),
    REVIEWED_HUMAN_RIGHTS_ISSUE("reviewed-human-rights-issue"),
    HRDD("hrdd"),
    SSM02("ssm02"),
    SSM03("ssm03"),
    EMPLOYEE_MGMT_PLAN("employee-mgmt-plan"),
    EMPLOYEE_MGMT_TARGET("employee-mgmt-target"),
    EMPLOYEE_MGMT_PERFORMANCE("employee-mgmt-performance"),
    EMPLOYMENT("employment"),
    DISABLED_EMPLOYEE("disabled-employee"),
    EMPLOYEE_TRAINING("employee-training"),
    EMPLOYEE_SAFETY("employee-safety"),
    EMPLOYEE_ENGAGEMENT_ASSESSMENT_RESULTS("employee-engagement-assessment-results"),
    DISCUSSION_OPERATION_AND_FINANCIAL_CONDITION("discussion-operation-and-financial-condition"),
    OVERALL_OPERATION("overall-operation"),
    OPERATIONAL_AND_FINANCIAL_PERFORMANCE("operational-and-financial-performance"),
    OPERATING_RESULTS_AND_PROFITS("operating-results-and-profits"),
    ASSETS_MGMT("assets-mgmt"),
    LIQUIDITY("liquidity"),
    DEBT_BURDEN_AND_OFF_BALANCE_SHEET_MGMT("debt-burden-and-off-balance-sheet-mgmt"),
    SSM04("ssm04"),
    CUSTOMER_MGMT_PLAN("customer-mgmt-plan"),
    CUSTOMER_MGMT_TARGET("customer-mgmt-target"),
    CUSTOMER_MGMT_PERFORMANCE("customer-mgmt-performance"),
    MATERIAL_AND_RELATED_PARTY_TRANSACTION("material-and-related-party-transaction"),
    OTHER_OPERATIONAL_AND_FINANCIAL_PERFORMANCE("other-operational-and-financial-performance"),
    DEBT_SECURITIES_ISSUANCE("debt-securities-issuance"),
    SSM05("ssm05"),
    SOCIAL_MGMT_PLAN("social-mgmt-plan"),
    SOCIAL_MGMT_TARGET("social-mgmt-target"),
    SOCIAL_MGMT_PERFORMANCE("social-mgmt-performance"),
    SSM06("ssm06"),
    OTHER_SOCIAL_MGMT_PLAN("other-social-mgmt-plan"),
    SSM07("ssm07"),
    NO_OF_LEGAL_SOCIAL_INCIDENT("no-of-legal-social-incident"),
    INCIDENT_SOCIAL_INFO("incident-social-info"),
    OTHER_MATERIAL_FACTS("other-material-facts"),
    OMF01("omf01"),
    OMF02("omf02"),
    INTERNAL_CONTROL("internal-control"),
    BOD_OPINION_SUMMARY("bod-opinion-summary"),
    IC01("ic01"),
    IC02("ic02"),
    DEFICIENCIES_INFO("deficiencies-info"),
    IC03("ic03"),
    IC04("ic04"),
    IC05("ic05"),
    GENERAL_INFORMATION("general-information"),
    GI01("gi01"),
    LEGAL_DISPUTES("legal-disputes"),
    LEGAL_DISPUTES_INFO("legal-disputes-info"),
    RELATED_PARTY_TRANSACTIONS("related-party-transactions"),
    RPT02("rpt02"),
    RPT03("rpt03"),
    RPT04("rpt04"),
    SECONDARY_MARKET("secondary-market"),
    FINANCIAL_INSTITUTION_REGULAR_CONTACT("financial-institution-regular-contact"),
    ESM06("esm06"),
    GH_GAS_MGMT_PLAN("gh-gas-mgmt-plan"),
    GH_GAS_COMPLIANCE_STANDARDS("gh-gas-compliance-standards"),
    GH_GAS_TARGET("gh-gas-target"),
    GH_GAS_NET_ZERO("gh-gas-net-zero"),
    GH_GAS_CARBON("gh-gas-carbon"),
    GH_GAS_OTHER("gh-gas-other"),
    GH_GAS_MGMT_PERFORMANCE("gh-gas-mgmt-performance"),
    ESM07("esm07"),
    OTHER_ENVIRONMENTAL_MGMT_PLAN("other-environmental-mgmt-plan"),
    ESM08("esm08"),
    NUMBER_OF_LEGAL_ENVIRONMENTAL_INCIDENT("number-of-legal-environmental-incident"),
    INCIDENT_ENVIRONMENTAL_INFO("incident-environmental-info"),
    CORPORATE_GOVERNANCE_STRUCTURE("corporate-governance-structure"),
    CGS01("cgs01"),
    FSFR01("fsfr01"),
    FSFR02("fsfr02"),
    BOARD_OF_DIRECTORS_INFORMATION("board-of-directors-information"),
    BODI01("bodi01"),
    BODI02("bodi02"),
    SAME_PERSON("same-person"),
    INDEPENDENT_CHAIRMAN("independent-chairman"),
    EXECUTIVE_COMMITTEE_MEMBER("executive-committee-member"),
    POWER_MEASURES_OF_BOARD_AND_MANAGEMENT("power-measures-of-board-and-management"),
    BODI03("bodi03"),
    SUBCOMMITTEES_INFORMATION("subcommittees-information"),
    SI01("si01"),
    SUB_COMMITTEE_ROLE("sub-committee-role"),
    SI02("si02"),
    EXECUTIVES_INFORMATION("executives-information"),
    EXI01("exi01"),
    PRESENT_EXECUTIVE_STRUCTURE("present-executive-structure"),
    EXI02("exi02"),
    EXI03("exi03"),
    OTHER_EXECUTIVE_REMUNERATION("other-executive-remuneration"),
    BENEFITS_PENDING_PAYMENT("benefits-pending-payment"),
    CURRENT_YEAR_ESTIMATION("current-year-estimation"),
    EMPLOYEES_INFORMATION("employees-information"),
    EMI01("emi01"),
    NUMBER_OF_EMPLOYEES("number-of-employees"),
    NUMBER_OF_EMPLOYEES_BY_POSITION_AND_DEPARTMENT("number-of-employees-by-position-and-department"),
    NUMBER_OF_MALE_EMPLOYEES_BY_POSITION("number-of-male-employees-by-position"),
    NUMBER_OF_FEMALE_EMPLOYEES_BY_POSITION("number-of-female-employees-by-position"),
    NUMBER_OF_EMPLOYEES_BY_DEPARTMENT("number-of-employees-by-department"),
    EMPLOYEES_SIGNIFICANT_CHANGES("employees-significant-changes"),
    EMI02("emi02"),
    EMPLOYEES_REMUNERATION_BY_DEPARTMENT("employees-remuneration-by-department"),
    EMPLOYEE_PVD_POLICY("employee-pvd-policy"),
    EMPLOYEE_PVD("employee-pvd"),
    OTHER_SIGNIFICANT_INFORMATION("other-significant-information"),
    OSI01("osi01"),
    ACCOUNTANT("accountant"),
    SECRETARY("secretary"),
    INTERNAL_AUDIT("internal-audit"),
    COMPLIANCE("compliance"),
    OSI02("osi02"),
    INVESTOR_RELATION_LIST("investor-relation-list"),
    OSI03("osi03"),
    COMPANY_AUDIT_INFO("company-audit-info"),
    SUBSIDIARY_COMPANY_AUDIT_INFO("subsidiary-company-audit-info"),
    OSI04("osi04"),
    REPRESENTATIVES_IN_THAILAND_INFO("representatives-in-thailand-info"),
    INDEPENDENT_DIRECTOR_SELECTION("independent-director-selection"),
    INDEPENDENT_DIRECTOR_SELECTION_CRITERIA("independent-director-selection-criteria"),
    INDEPENDENT_DIRECTOR_BUSINESS_RELATIONSHIP("independent-director-business-relationship"),
    EXECUTIVES_SELECTION("executives-selection"),
    EXECUTIVES_SELECTION_PROCESS("executives-selection-process"),
    NUMBER_OF_DIRECTOR_FROM_MAJOR_SHAREHOLDER("number-of-director-from-major-shareholder"),
    MINOR_SHAREHOLDER_RIGHTS("minor-shareholder-rights"),
    BOARD_OF_DIRECTORS_PERF_SUMMARY("board-of-directors-perf-summary"),
    BOARD_OF_DIRECTORS_PERF_SUMMARY_SUB_SECTION("board-of-directors-perf-summary-sub-section"),
    BODPS01("bodps01"),
    BODPS0101("bodps0101"),
    DIRECTORS_QUALIFICATION_SPECIFICATION("directors-qualification-specification"),
    BODPS0103("bodps0103"),
    DIRECTOR_EVALUATION_CRITERIA("director-evaluation-criteria"),
    DIRECTOR_EVALUATION("director-evaluation"),
    BODPS0102("bodps0102"),
    DIRECTOR_DEVELOPMENT("director-development"),
    BODPS03("bodps03"),
    OVERSIGHT_MECHANISM("oversight-mechanism"),
    SHAREHOLDERS_AGREEMENT("shareholders-agreement"),
    BODPS02("bodps02"),
    BODPS0201("bodps0201"),
    DIRECTOR_MEETING_ATTENDANCE_SUB_SECTION("director-meeting-attendance-sub-section"),
    BODPS0202("bodps0202"),
    DIRECTOR_REMUNERATION_CHARACTERISTIC("director-remuneration-characteristic"),
    PENDING_PAYMENT("pending-payment"),
    BODPS04("bodps04"),
    BODPS0401("bodps0401"),
    CONFLICTS_OF_INTEREST_PREVENTION("conflicts-of-interest-prevention"),
    NUMBER_OF_CONFLICTS_OF_INTEREST_INFO("number-of-conflicts-of-interest-info"),
    BODPS0402("bodps0402"),
    SEEK_BENEFITS_INSIDE_INFO_OPERATIONS("seek-benefits-inside-info-operations"),
    NUMBER_OF_SEEK_BENEFITS_INSIDE_INFO("number-of-seek-benefits-inside-info"),
    BODPS0403("bodps0403"),
    ANTI_CORRUPTION("anti-corruption"),
    NUMBER_OF_ANTI_CORRUPTION_INFO("number-of-anti-corruption-info"),
    BODPS0404("bodps0404"),
    WHISTLEBLOWING_OPERATIONS("whistleblowing-operations"),
    NUMBER_OF_WHISTLEBLOWING_INFO("number-of-whistleblowing-info"),
    OTHER_COMPLIANCE_MONITORING("other-compliance-monitoring"),
    AUDIT_COMMITTEES_PERF_SUMMARY("audit-committees-perf-summary"),
    APS01("aps01"),
    APS02("aps02"),
    SUBCOMMITTEES_PERF_SUMMARY("subcommittees-perf-summary"),
    SPS01("sps01"),
    SUB_COMMITTEE_MEETING("sub-committee-meeting"),
    RESEARCH_COST("research-cost");

    private final String value;

    private static final Map<String, RemarkSection> keyMap = new HashMap<>();

    static {
        for (RemarkSection enumValue : RemarkSection.values()) {
            keyMap.put(toKebabCase(enumValue.name()), enumValue);
        }
    }

    RemarkSection(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static RemarkSection getByKey(String key) {
        return keyMap.get(key);
    }

    private static String toKebabCase(String input) {
        return input.toLowerCase().replace('_', '-');
    }

    public static RemarkSection fromValue(String value) {
        for (RemarkSection session : RemarkSection.values()) {
            if (session.getValue().equalsIgnoreCase(value)) {
                return session;
            }
        }
        return null;
    }

    public static RemarkSection getKeyByValue(String value) {
        for (RemarkSection enumValue : RemarkSection.values()) {
            if (enumValue.getValue().equals(value)) {
                return enumValue;
            }
        }
        return null;
    }
}
